name: Release LookyLoo

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2022

    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip dalamud_dev

    - name: Build with dotnet
      env:
        DALAMUD_HOME: ${{ github.workspace }}\dalamud_dev
      run: dotnet build SamplePlugin.sln --configuration Release

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: download/latest.zip
        generate_release_notes: true
